import { form, get, post, route } from "remix/routes";

export const routes = route({
  assets: get("/assets/*path"),
  home: get("/"),
  login: get("/login"),
  settings: form("/settings"),
  myUploads: get("/my-uploads"),
  folders: get("/folders"),
  folder: form("/folder/*path"),
  file: get("/file/*path"),
  legacyWad: get("/wad/:fileId"),
  legacyWadTexture: get("/wad/:fileId/texture/:textureIndex"),
  auth: route("/auth", {
    fourm: get("/4orm"),
    fourmCallback: get("/4orm/callback"),
    cliAuthorize: get("/cli/authorize"),
    cliCallback: get("/cli/callback"),
  }),
  admin: route("/admin", {
    jobs: form("/"),
    import: form("/import"),
    inbox: form("/inbox"),
    archives: form("/archives"),
    scanSettings: form("/scan-settings"),
    users: get("/users"),
    orphans: form("/orphans"),
  }),
  api: route("/api", {
    upload: post("/upload"),
    import: post("/import"),
    lucky: post("/lucky"),
    folder: post("/folder"),
    folderMove: post("/folder/move"),
    folderDownload: get("/folder/download/*path"),
    wadTexture: get("/wad/:fileId/texture/:textureIndex"),
    cli: route("/cli", {
      whoami: get("/whoami"),
      foldersGet: get("/folders"),
      foldersPost: post("/folders"),
      folderManage: post("/folder/manage"),
      manifest: post("/manifest"),
      upload: post("/upload"),
      finalize: post("/finalize"),
    }),
  }),
});
